package gui;

import classes.SeatMap;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;
import model.DbConnect;

public class show_select_gui extends javax.swing.JFrame {

//Private variables
    private dashBoard_gui dashboard;

//Load the show table dynamically by retrieving them from the database
    private void loadShowTable() {
        try {
            ResultSet rs = DbConnect.createConnection().prepareStatement("SELECT * FROM `show`").executeQuery();
            DefaultTableModel dtm = (DefaultTableModel) table_extrashow.getModel();
            dtm.setRowCount(0);
            while (rs.next()) {
                //Create new vector for each record of the table
                Vector v = new Vector();
                v.add(rs.getString("show_id"));
                v.add(rs.getString("show_name"));
                v.add(rs.getString("show_date"));
                dtm.addRow(v);
            }
            DbConnect.closeConnection();
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

//Load the show table dynamically according to a 'search criteria' by retrieving them from the database
    private void loadShowTable(String searchTerm) {
        try {
            PreparedStatement stmt = DbConnect.createConnection().prepareStatement("SELECT * FROM `show` WHERE `show_id` LIKE ? OR `show_name` LIKE ? OR `show_date` LIKE ?");
            stmt.setString(1, searchTerm + "%");
            stmt.setString(2, searchTerm + "%");
            stmt.setString(3, searchTerm + "%");
            ResultSet rs = stmt.executeQuery();
            DefaultTableModel dtm = (DefaultTableModel) table_extrashow.getModel();
            dtm.setRowCount(0);
            while (rs.next()) {
                //Create new vector for each record of the table
                Vector v = new Vector();
                v.add(rs.getString("show_id"));
                v.add(rs.getString("show_name"));
                v.add(rs.getString("show_date"));
                dtm.addRow(v);
            }
            DbConnect.closeConnection();
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    public show_select_gui() {
        initComponents();
        loadShowTable();
    }

    public show_select_gui(dashBoard_gui dash) {
        this.dashboard = dash;
        initComponents();
        loadShowTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        tf_extrashow_search = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_extrashow = new javax.swing.JTable();
        btn_extrashow_select = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Select Show");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-search-23.png"))); // NOI18N

        tf_extrashow_search.setForeground(new java.awt.Color(102, 102, 102));
        tf_extrashow_search.setText("Search");
        tf_extrashow_search.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_extrashow_searchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_extrashow_searchFocusLost(evt);
            }
        });
        tf_extrashow_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_extrashow_searchKeyReleased(evt);
            }
        });

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });
        jScrollPane1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jScrollPane1KeyPressed(evt);
            }
        });

        table_extrashow.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Show-ID", "Show name", "Show date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_extrashow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_extrashowMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_extrashow);

        btn_extrashow_select.setText("Select");
        btn_extrashow_select.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_extrashow_selectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_extrashow_search))
                    .addComponent(btn_extrashow_select, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf_extrashow_search)
                    .addComponent(jLabel30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_extrashow_select, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tf_extrashow_searchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_extrashow_searchFocusGained
        if (tf_extrashow_search.getText().equals("Search")) {
            tf_extrashow_search.setText("");
        }
        tf_extrashow_search.setForeground(Color.black);
    }//GEN-LAST:event_tf_extrashow_searchFocusGained

    private void tf_extrashow_searchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_extrashow_searchFocusLost
        if (tf_extrashow_search.getText().isBlank()) {
            tf_extrashow_search.setText("Search");
            tf_extrashow_search.setForeground(new Color(102, 102, 102));
        } else {
            tf_extrashow_search.setForeground(Color.black);
        }
    }//GEN-LAST:event_tf_extrashow_searchFocusLost

    private void tf_extrashow_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_extrashow_searchKeyReleased
        //Checking if the search field is empty or not, and invoking the respective methods to fill the table
        if (!tf_extrashow_search.getText().isEmpty() || !tf_extrashow_search.getText().equals("Search")) {
            loadShowTable(tf_extrashow_search.getText());
        } else {
            loadShowTable();
        }

    }//GEN-LAST:event_tf_extrashow_searchKeyReleased

    private void btn_extrashow_selectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_extrashow_selectActionPerformed
        int r = table_extrashow.getSelectedRow();
        if (r != -1) {
            String showId = table_extrashow.getValueAt(r, 0).toString();
            dashboard.clearSeatFields();
            dashboard.label_book_showid.setText(showId);
            dashboard.setSeatMap(new SeatMap(Integer.parseInt(showId), dashboard));// Create new seatMap object replacing the previous one
            dashboard.initSeatAvailability(); //Edit the seat colors to the selected show
            this.dispose();
        }
    }//GEN-LAST:event_btn_extrashow_selectActionPerformed

    private void jScrollPane1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jScrollPane1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1KeyPressed

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked

    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void table_extrashowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_extrashowMouseClicked
        if (evt.getClickCount() == 2) {
            int r = table_extrashow.getSelectedRow();
            if (r != -1) {
                String showId = table_extrashow.getValueAt(r, 0).toString();
                dashboard.clearSeatFields();
                dashboard.label_book_showid.setText(showId);
                dashboard.setSeatMap(new SeatMap(Integer.parseInt(showId), dashboard));// Create new seatMap object replacing the previous one
                dashboard.initSeatAvailability(); //Edit the seat colors to the selected show
                this.dispose();
            }
        }
    }//GEN-LAST:event_table_extrashowMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (UnsupportedLookAndFeelException e) {
            e.printStackTrace();
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new show_select_gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_extrashow_select;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_extrashow;
    private javax.swing.JTextField tf_extrashow_search;
    // End of variables declaration//GEN-END:variables
}
