package gui;

import com.formdev.flatlaf.FlatLightLaf;
import javax.swing.UIManager;

public class Splash extends javax.swing.JFrame {

    /**
     * Creates new form Splash
     */
    public Splash() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jProgressBar1 = new javax.swing.JProgressBar();
        label_text = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jProgressBar1.setForeground(new java.awt.Color(141, 38, 135));
        jProgressBar1.setPreferredSize(new java.awt.Dimension(500, 20));
        jProgressBar1.setStringPainted(true);
        jPanel1.add(jProgressBar1);
        jProgressBar1.setBounds(30, 510, 540, 20);

        label_text.setText("Loading...");
        jPanel1.add(label_text);
        label_text.setBounds(30, 490, 500, 16);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pic3.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(60, 20, 490, 480);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (Exception e) {
            e.printStackTrace();
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Splash s = new Splash();
                
                s.setVisible(true);
                Thread t = new Thread(() -> {

                    for (int i = 0; i < 100; i++) {
                        if (i < 45) {
                            s.jProgressBar1.setValue(i);
                            try {
                                s.label_text.setText("Loading Assests...");
                                Thread.sleep(50);
                            } catch (Exception e) {
                                e.printStackTrace();
                            }
                        } else if (i >= 45 && i < 58) {
                            s.jProgressBar1.setValue(i);
                            try {
                                s.label_text.setText("Loading Dependables...");
                                Thread.sleep(75);
                            } catch (Exception e) {
                                e.printStackTrace();
                            }
                        } else if (i >= 58 && i < 98) {
                            s.jProgressBar1.setValue(i);
                            try {
                                s.label_text.setText("Setting up database connections...");
                                Thread.sleep(25);
                            } catch (Exception e) {
                                e.printStackTrace();
                            }
                        } else if (i == 98) {
                            s.jProgressBar1.setValue(i);
                            try {
                                s.label_text.setText("Almost there...");
                                Thread.sleep(250);
                            } catch (Exception e) {
                                e.printStackTrace();
                            }
                        } else if (i == 99) {
                            s.jProgressBar1.setValue(i);
                            try {
                                s.label_text.setText("Done...");
                                Thread.sleep(350);
                            } catch (Exception e) {
                                e.printStackTrace();
                            }
                        }
                    }

                    new login_gui().setVisible(true);
                    s.dispose();
                });
                t.start();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel label_text;
    // End of variables declaration//GEN-END:variables
}
